services:
  app:
    image: ghcr.io/longevity-genie/biothings-mcp:latest
    ports:
      - "8000:8000"
    environment:
      - MCP_PORT=8008
    networks:
      - mcp-network

  inspector:
    image: mcp/inspector
    ports:
      - "6274:6274"
      - "6277:6277"
    environment:
      - MCP_SERVER_URL=http://app:8000/mcp
    depends_on:
      - app
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 